### frontend build start
FROM node:20.16.0 as frontend

WORKDIR /app

COPY . /app/
RUN \
    cd ui &&\
    npm i &&\
    npm run build
### frontend build end

### go build start
FROM golang:1.22-alpine as builder

WORKDIR /app

RUN go build -o certimate
### go build end

### app images
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/certimate .

ENTRYPOINT ["./certimate", "serve", "--http", "0.0.0.0:8090"]